version: "3.8"

services:
  postgres_nlw:
    container_name: postgres_nlw
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_nlw
